# Generated by Django 2.0.2 on 2018-03-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='博客题目未设置', max_length=200),
        ),
    ]
